name: deploy

on:
    push:
    workflow_dispatch:

env:
  TZ: Canada/Atlantic

jobs:
    build:
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Git Configuration
              run: |
                git config --global core.quotePath false
                git config --global core.autocrlf false
                git config --global core.safecrlf true
                git config --global core.ignorecase false

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build
              run: hugo --minify

            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
              with:
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  EXTERNAL_REPOSITORY: yizhezhong/yizhezhong.github.io
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./public